# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('life_stage', models.CharField(choices=[('Kids', 'Kids'), ('High School', 'High School'), ('College', 'College'), ('Single', 'Single'), ('Married', 'Married'), ('Solo Parent', 'Solo Parent'), ('Senior', 'Senior'), ('Other', 'Other')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SundayService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('schedule', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VictoryGroupLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('life_stage', models.CharField(choices=[('Kids', 'Kids'), ('High School', 'High School'), ('College', 'College'), ('Single', 'Single'), ('Married', 'Married'), ('Solo Parent', 'Solo Parent'), ('Senior', 'Senior'), ('Other', 'Other')], max_length=20)),
                ('vg_venue', models.CharField(max_length=200, verbose_name='Victory group venue')),
                ('vg_day', models.CharField(choices=[('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat')], max_length=3, verbose_name='Victory group day')),
                ('vg_time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=10, verbose_name='Victory group time')),
                ('service_attended', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SundayService')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='disciple',
            name='service_attended',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SundayService'),
        ),
        migrations.AddField(
            model_name='disciple',
            name='victory_group_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.VictoryGroupLeader'),
        ),
    ]
