# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciple',
            options={'ordering': ('last_name',)},
        ),
        migrations.AlterModelOptions(
            name='sundayservice',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='victorygroupleader',
            options={'ordering': ('last_name',)},
        ),
        migrations.AlterField(
            model_name='disciple',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='victorygroupleader',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
