# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161003_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Member'),
        ),
    ]
