# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161003_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Member', verbose_name='VG Leader or Leadership Group Leader'),
        ),
        migrations.AlterField(
            model_name='victorygroup',
            name='month_started',
            field=models.CharField(blank=True, choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('last_name', 'first_name', 'birthdate')]),
        ),
    ]
