# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161012_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='victorygroup',
            options={'ordering': ('leader',)},
        ),
        migrations.AlterField(
            model_name='member',
            name='life_stage',
            field=models.CharField(choices=[('Kids', 'Kids'), ('High School', 'High School'), ('College', 'College'), ('Single', 'Single'), ('Married', 'Married'), ('Solo Parent', 'Solo Parent'), ('Senior', 'Senior'), ('Widow', 'Widow'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('last_name', 'first_name', 'gender', 'birthdate')]),
        ),
    ]
