# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161118_0940'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([]),
        ),
    ]
