# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161119_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIDCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vid_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vid_month', models.PositiveIntegerField(blank=True, null=True)),
                ('vid_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='member',
            name='victory_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Victory ID'),
        ),
    ]
