# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170124_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='victory_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Victory ID'),
        ),
    ]
